### ISSUE TITLE
Text field needs a bit of tweaking

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#139]
![image](https://user-images.githubusercontent.com/59652042/77570755-f7ef5200-6ed4-11ea-8fee-45c1887a39b0.png)
- Text field should be the same distance from each side, now it's too close to the right
- Text field should scale to screen before requiring a scroll bar

**Comment by zilahir** [comment]
1st point is done.

**Comment by oittinen** [comment]
I played around with it a bit since it looked like it's not quite right yet. I changed .Preview_previewContainer__2UfGi margin-left from -30px to -34px and it seems like the distances from the sides are equal. Then I changed .TextEditor_textEditorContainer__o8XVr margin from "0 20px" to "0 50px" and now it looks more balanced since the text box is at about the same distance from the sidebars as the stuff in the sidebars are from the main content area.

**Comment by zilahir** [comment]
check now!
