### ISSUE TITLE
Remote scaling issue

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#144]
- The "login" screen doesn't fit on my phone screen vertically, it should be responsive somehow so that all the elements are visible on any phone screen.
- Similar issue with the remote view itself, I seem to be able to scroll the remote view up and down a bit since I'm guessing my screen isn't as tall as the page is designed to

**Comment by zilahir** [comment]
@oittinen please share a screenshot of the 1st point. 2nd point is taken care of.

**Comment by zilahir** [comment]
@oittinen please test the prompter mobile screen when you have to type the slug in the input field. I am not sure i could connect the `return` btn for some reason, but when the keyboard view is open, you should be able to scroll.

**Comment by oittinen** [comment]
yeah the "Go" button in the mobile keyboard doesn't do anything

maybe if there was more of a margin on the bottom of the page, the button would be visible even with the keyboard open?
