### ISSUE TITLE
"Flip for reflection" does nothing

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#146]

**Comment by oittinen** [comment]
Seems to work well in the scroller, just needs to do the same in the preview

**Comment by oittinen** [comment]
when the content is flipped, it should start at "the end", meaning the beginning of the content and scrolling should probably be reversed, too, so that when you use it in a mirror, it looks like it's the right side up

**Comment by zilahir** [comment]
done, needs to be tested
