### ISSUE TITLE
ID slugs seem to get increasingly complex

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#156]
![image](https://user-images.githubusercontent.com/59652042/77680374-88dd3080-6f9c-11ea-8654-b3a2413f30a6.png)

When I refresh the page, the ID is 8 characters long (69c955f3), but when I start a new one by clicking New and clearing the old one, the ID is 8+4+4+4+12 characters long (ad3fed67-5ee9-425f-be59-5106830d1094)

**Comment by zilahir** [comment]
done.
