### ISSUE TITLE
feedback of successful update 

### ISSUE THREAD

**Issue by zilahir** [zilahir/teleprompter#167]
i have implemented both the server side and the client side functions of updating a prompter. right now if you press the update button, the database will be updated with the new values, but there is no feedback for the user that anything has happened. 

We should provide some type of success message somewhere ?

**Comment by oittinen** [comment]
I think in the editor view the update button should be only visible when the user has made changes and once the updates have been sent, it should disappear.

In the scroller view, maybe a "refresh" button should appear in the top bar when there are updates. This means we need to make that appear there instantly when updates have been sent. I can design the button if this is possible.

**Comment by zilahir** [comment]
the editor side is done, i will add a floating button. how about placing it to the bottom-right corner?

**Comment by zilahir** [comment]
done.
