### ISSUE TITLE
Some little visual tweaks

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#176]
I played around with the editor page in Inspect to try and balance the visuals out a bit more, so:

- The text editor needs a solid 2px border in #4d4d4d
- The weight of .labelText in the sidebar should be 400
- The padding of ActionSidebar_testAnimation should be 10px 0px
- Input_labelText (Remote control address etc) should have a font-size of 14px and the margin-bottom should be changed to 10px
- The savedItems font-size (in the Load dropdown) should be 15px
- In the saved items, the "play" icon is some other icon, rotated 90 degrees. This results in it looking like it's just a little bit lower than it should be in relation to the delete icon. I tried adding 2px padding-right to it (so it's on the bottom due to the rotation) and that seemed to work fine.
- In the savedItems, change the project name padding-left to 20px (just on the left, the 10px is otherwise good)
- In the savedItems, change the icon margin-left to 15px
- Remove the border-bottom that's between the items in the saveditems dropdown

That's it! (for now)

**Comment by zilahir** [comment]
done #177
