### ISSUE TITLE
Stream address copy button copies the wrong URL

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#243]
the /player part is missing from the copied URL

**Comment by zilahir** [comment]
done

**Comment by oittinen** [comment]
Okay, if I copy and paste the stream address into another tab before clicking the Open button, it's just empty. I'm guessing the stream isn't actually created before clicking Open, so going to that URL before that won't work. We should figure out what to do about this. Maybe there should be a "Create" button before you can get a link or something.

**Comment by zilahir** [comment]
well that is true. everthing is created in the database by clicking `Open`. What i would do is to implement a gaurd within the stream link, if no prompter with that slug exists?

**Comment by oittinen** [comment]
How about this? The link fields, including the copying buttons, are at .5 opacity and unclickable, before you first click a button that's the same as "Open" but says "Create" and doesn't open a new tab. Then, when the prompter has been created, the button says "Open" and works as it does now. This way you first have to create the prompter feed before you can copy a link to it. This would of course mean changing the guide texts as well, but that's not a problem.

**Comment by zilahir** [comment]
done.
