### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#248]
Add the following code as the first thing under <head>
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-163692111-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-163692111-1');
</script>
`

**Comment by zilahir** [comment]
we have to do this a bit differently in react world, but sure thingie.

**Comment by oittinen** [comment]
There's no data in Analytics yet, so I have no idea what we should do.

**Comment by oittinen** [comment]
No wait, that was incorrect. There's some basic visitor data from today. Let's keep this issue open for now in case we need to adjust something.

**Comment by zilahir** [comment]
@oittinen is this working properly now?
