### ISSUE TITLE
Add instructions etc

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#25]
![image](https://user-images.githubusercontent.com/59652042/74928632-8fe3b280-53e2-11ea-905a-2aef0af311a3.png)

For the top:

Write or paste your script into the input field below. You can adjust the prompter settings on the left and see a preview on the top right. Press Play to open the prompter in a new tab. If you make changes, press Update to send those changes to the prompter feed. You can open the prompter feed in any device by opening the Stream address in a web browser. To use your phone as a remote control, open the Remote control address in your phone's web browser.

For the side bar:

This is an alpha release, which means it's not finished. You can report bugs, give feedback or suggest features by emailing info@prompter.me.

**Comment by zilahir** [comment]
done.
