### ISSUE TITLE
create image for sharing

### ISSUE THREAD

**Issue by zilahir** [zilahir/teleprompter#256]
[reference](https://developers.facebook.com/docs/sharing/webmasters/images/)

**Comment by oittinen** [comment]
![prompterme-sharing](https://user-images.githubusercontent.com/59652042/79745585-41cf2a80-8311-11ea-9e4c-b08f642835f4.png)

**Comment by oittinen** [comment]
![prompterme-sharing](https://user-images.githubusercontent.com/59652042/79745772-8f4b9780-8311-11ea-86f7-3ab84bfa4743.png)
