### ISSUE TITLE
Guide text update

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#259]
Change the guide text to the following to match the current functionality:

"Write or paste your script into the input field below. You can adjust the prompter settings on the left and see a live preview on the top right. Press "Create" to create you prompter. You can then press "Open" to open the prompter in a new tab, or copy the "Stream address" to open the prompter on another computer. You can also copy the "Remote phone address" to open a remote control on your phone. If you make changes to your prompter, click "Update" in your editor first and then in your prompter to apply the updates."

Include the "Hide this guide" link

**Comment by zilahir** [comment]
done.
