### ISSUE TITLE
More alignment tweaking

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#26]
![image](https://user-images.githubusercontent.com/59652042/74930223-cec73780-53e5-11ea-84cb-aa00b71fbd49.png)

Now that the slider labels are aligned with the sliders, they no longer align with the other labels on the sidebar. I didn't consider that. Maybe just move the labels back to where they were and leave the numbers as they are now, so that all the labels line up on the left but the numbers still line up with the slider.

**Comment by zilahir** [comment]
done.
