### ISSUE TITLE
investigate scrolling performance

### ISSUE THREAD

**Issue by zilahir** [zilahir/teleprompter#265]

**Comment by zilahir** [comment]
i have adjusted this slightly, needs testing

**Comment by oittinen** [comment]
When I click Create Prompter, it just spins the loader forever, so I can't test the scroller atm

**Comment by oittinen** [comment]
At mid-speed (4 or 5) it's very slow. At higher speeds it simply doesn't move, until I hit pause and then it jumps forward.

**Comment by oittinen** [comment]
It's MUCH better, but at least for me it seems like it's really slow right now. Even at maximum speed it's fairly slow.

**Comment by zilahir** [comment]
we need to play with the scroller speed settings
