### ISSUE TITLE
Implement font selection

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#322]
Only changes the scroller font

Sans by default
Mono: Courier Prime Regular: https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom&query=courier
Serif: Crimson Pro Medium Roman: https://fonts.google.com/specimen/Crimson+Pro?preview.text_type=custom&query=crimson

**Comment by zilahir** [comment]
fons added

**Comment by oittinen** [comment]
Seems to work fine otherwise, but the Mono and Serif fonts should have font-weight 400 instead of 600. Actually the sans font could have a font-weight of 500.

**Comment by zilahir** [comment]
done
