### ISSUE TITLE
Implement Alignment

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#323]
Scroller text alignment selection in editor, left by default

**Comment by oittinen** [comment]
I don't see the alignment changing in the preview or the scroller.

**Comment by zilahir** [comment]
done.

**Comment by oittinen** [comment]
Changing alignment doesn't trigger the "send updates" thing so the change isn't updated even when opening the prompter again. This also applies to the other new settings like color scheme and font.

**Comment by zilahir** [comment]
i'll take a look!

**Comment by zilahir** [comment]
@oittinen test this again pls thanks you kiitos danke köszi

**Comment by zilahir** [comment]
@oittinen tell me when u had the change to test dis. tak!

**Comment by oittinen** [comment]
Ok now it triggers the "send updates" button, but the update button in the scroller is broken. It looks like this:
![image](https://user-images.githubusercontent.com/59652042/95750122-592a1780-0ca5-11eb-9aa5-35f469932e9d.png)
and it crashes the scroller when clicked.
