### ISSUE TITLE
Design changes for v2

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#324]
Small changes to at least:

- Icons
- Font sizes/weights
- Input styles
- Button styles
- Dropdown styles

**Comment by oittinen** [comment]
UI comments:
- There should be one empty segment there by default
- Add segment and Add pause could have the same kind of hover effect as the top menu buttons
- Add segment button should be aligned on the left with the segments
- The left side of the logo should be aligned with the left side of the controls
- "Add segment name" should be an input placeholder, now it has to be manually replaced, since if you just delete it, it comes back
- The main preview font seems to be some kind of serif font, even when something else is selected. Reflection looks right though.
- Icons should be material icons (Add segment, Add pause, Close icon for deleting segments, 
- How to Use button should be aligned on the right with preview etc.
- There seems to be a delay when clicking "Create Prompter", perhaps a loader on top of the button before it changes to Open Prompter?
- Open Prompter button has a typo (Propmter)
- There's no Send Updates button yet

**Comment by zilahir** [comment]
@oittinen can you tell me please again the icon names? 

either from here: https://react-icons-kit.now.sh/iconset/md

or here: https://material-ui.com/components/material-icons/

thanks!

**Comment by zilahir** [comment]
@oittinen everything had been deployed, except the icons, i'll need some additional help there :)

**Comment by zilahir** [comment]
@oittinen please check the issues with label `needs testing`, and close them, if you are satisfied. :) thanxxxx

**Comment by oittinen** [comment]
I used the material-ui.com list, I think this is all of the icons now:

**Editor**

- Add Segment: PostAdd
- Add Pause: PlaylistAdd
- Send Updates: Refresh
- Open Prompter: Launch
- Create Prompter: MovieFilter
- Delete segment/pause: Close
- Git: GitHub


**Scroller**

- Update: Refresh


**Mobile**

- Play: PlayArrow
- Pause: Pause
- Navigate up: KeyboardArrowUp
- Navigate down: KeyboardArrowDown
- Slower: FastRewind
- Faster: FastForward
- Info: Info

**Comment by oittinen** [comment]
I did some shit with inspect to try and align and tighten everything up:

- Changed the padding of .Segment_oneSegment from 15px to 5px
- Added margin-top: 4px to .Segment_segmentHeader
- Added margin-top: 4px .Segment_deleteBtn
- Changed the margin-top of .Segment_segmentBody from 15px to 10px
- Changed the top and bottom padding of .Preview_innerContainer from 50px to 20px
- Changed the padding-left of Preview_previewRoot from 15px to 48px
- Changed the padding on the sides of Preview_innerContainer from 80px to 20px
- Changed the top and bottom padding of the segments and pauses from 16px to 8px
- Changed the padding-top of .EditorSidebar_editorSidebarContainer from 40px to 20px
- Changed the top and bottom margin of .ActionSidebar_innerContainer from 50px to 30px

If I did something in a dumb way please inform me or ignore it, but I think it looks better like that and works better with a smaller resolution.

**Comment by zilahir** [comment]
- ~~Changed the padding of .Segment_oneSegment from 15px to 5px~~
- ~~Added margin-top: 4px to .Segment_segmentHeader~~
- ~~Added margin-top: 4px .Segment_deleteBtn~~ - *i have adjusted the alignment, but adding margin is usually the wrong way of aligning, i have done it in a different way*
- ~~Changed the margin-top of .Segment_segmentBody from 15px to 10px~~
- ~~Changed the top and bottom padding of .Preview_innerContainer from 50px to 20px~~
- ~~Changed the padding-left of Preview_previewRoot from 15px to 48px~~ *that `padding 15` is part of the `Grid`. Modifying that will have effect on the entire layout everywhere in the app. Lets discuss whats the goal here, and solve it in a different way.*
- ~~Changed the padding on the sides of Preview_innerContainer from 80px to 20px~~ *ive added `padding 0 20px` to that element, but it didnt have `padding 0 80px`. let's double check this*
- ~~Changed the top and bottom padding of the segments and pauses from 16px to 8px~~
- ~~Changed the padding-top of .EditorSidebar_editorSidebarContainer from 40px to 20px~~
- ~~Changed the top and bottom margin of .ActionSidebar_innerContainer from 50px to 30px~~

**Comment by oittinen** [comment]
![image](https://user-images.githubusercontent.com/59652042/93428504-41d75480-f8c8-11ea-9f90-a2ac2b7c7d3d.png)
The goal of the padding stuff is to have these four distances be the same.

**Comment by zilahir** [comment]
@oittinen and which one is correct? the padding in the sidebars, or the padding in the middle?

**Comment by oittinen** [comment]
The padding in the sidebars is perfect imo, in the middle the biggest issue is that the left and right padding are different
