### ISSUE TITLE
Icon alignment issue

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#360]
Icon divs are 3px too high for some reason. Investigate please!

**Comment by zilahir** [comment]
the problem with the icons are still that even if their container is a fixed size, the actual svg within is not. 

![image](https://user-images.githubusercontent.com/6687149/95907745-b1940e80-0da4-11eb-8fbc-1fb37752af32.png)


though i have explicitly set the iconcontainer divs sizes to 24px.
