### ISSUE TITLE
Player doesn't load on android tablet

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#400]
Opening a player address on my tablet's Chrome browser shows just an empty white page. Not sure about how we can debug this but let's try to figure it out.

**Comment by zilahir** [comment]
@oittinen  can you provide me that player slug?

**Comment by oittinen** [comment]
I don't think I saved it anywhere, I'll test again properly tomorrow and give more info

**Comment by zilahir** [comment]
let's test it together, at least on ipad i was not able to repro.

**Comment by oittinen** [comment]
It works in incognito on my tablet now! I'll try to delete any cached data and test again.

**Comment by zilahir** [comment]
i might gonna increase the rehydratet version number of the store, so if it's new, it will just create a new persisted value, that would avoid the application to crash when those values are missing. 

guess i should do that? 🤔

**Comment by oittinen** [comment]
I don't really understand what that means but ok 😄 Seems like it works now that I emptied the browsing history and everything!
