### ISSUE TITLE
Little visual tweaks

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#420]
- The Add segment and Add pause button labels are a bit low and a bit far away from the icon. Change the Preview_button "top" value from 2px to -3px and the Preview_segmentsHeader left margin from 10px to 5px
- Chrome renders the Create Prompter / Open Prompter / Send Updates buttons kinda smudgy. Change the font weight from 600 to 500

That's it for now :D

**Comment by zilahir** [comment]
I have fixed the first bulletpoint differently, the 2px hacky way got removed.
