### ISSUE TITLE
The content doesn't save or update

### ISSUE THREAD

**Issue by oittinen** [zilahir/teleprompter#466]
I can change the settings of the scroller and update the stream, but if I change the script's content, it doesn't get updated once the prompter is created.

Also, once I've saved a project, making changes to the script and saving again does nothing. It seems that once the content is created, whether that's saving a script or creating a prompter, it can't be altered anymore.

**Comment by zilahir** [comment]
in progress!

**Comment by oliversum-ch** [comment]
Hey @zilahir, any news on that? I can replicate this bug unfortunately...
Thanks!

**Comment by Cypris2010** [comment]
I can replicate this bug, too.

**Comment by zilahir** [comment]
hey guys! thanks for reporting this, i'll try to push the fix as soon as i can! thank you!

**Comment by oliversum-ch** [comment]
Hey @zilahir, do you already know when you'll be able to work on this great teleprompter again?
Thanks so much for a brief update!

**Comment by zilahir** [comment]
hey guys! 

sorry, for took it this long, but ive managed to find the time for the issue you were reporting here, and attempted to fix it. please go ahead and check it out, it should be good now. i am closing this ticket now. if you still find glitches about this, feel free to comment here, and i'll reopen. 

thanks for the patience.
